## 1. WAP to create a numpy array and find indices of non-zero elements

In [3]:
import numpy as np
arr = np.array([[0, 8, 0], [7, 0, 0], [-5, 0, 1]]) 
  
print ("Input  array : \n", arr) 
    
out = np.transpose(np.nonzero(arr)) 
print ("Indices of non zero elements : ", out) 

Input  array : 
 [[ 0  8  0]
 [ 7  0  0]
 [-5  0  1]]
Indices of non zero elements :  [[0 1]
 [1 0]
 [2 0]
 [2 2]]


## 2. WAP to create a numpy to create a 3x3 identity matrix

In [36]:
arr=np.identity(3)
print('3x3 matrix:')
print(arr)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3.WAP to create a numpy to create a 3x3x3 array with random values

In [39]:
A = np.random.randint(10, size=(3, 3,3))
print(A)

[[[1 3 0]
  [3 8 6]
  [5 1 6]]

 [[5 8 6]
  [7 7 3]
  [4 3 9]]

 [[9 6 2]
  [8 3 8]
  [8 4 4]]]


## 4.WAP to create a numpy to create a random vector of size 30 and find the mean value

In [8]:
x = np.random.random(30)
print(x)
sum=0
for i in x:
    sum=sum+i
print("sum=",sum)
m=sum/30
print("mean of random 30 vectors=",m)

[0.33890649 0.26005828 0.06259775 0.54187458 0.56600062 0.5093039
 0.60944464 0.81983143 0.83757829 0.40845268 0.61730015 0.91084582
 0.31054231 0.08048973 0.97160564 0.83578037 0.43690142 0.21824104
 0.53312768 0.60769952 0.87076518 0.60304682 0.47485356 0.49390058
 0.34228109 0.23627363 0.6406051  0.68685809 0.32457508 0.33493168]
sum= 15.484673147114988
mean of random 30 vectors= 0.5161557715704996


## 5.WAP to create a numpy to multiply a 5x3 matrix by a 3x2 matrix

In [33]:
A = np.random.randint(10, size=(5, 3))
print("Matrix A: \n", A)
B = np.random.randint(10, size=(3, 2))
print ("Matrix B:\n",B)
mul=np.dot(A,B)
print("Multiplication matrix:\n",mul)

Matrix A: 
 [[3 4 0]
 [5 9 9]
 [3 4 4]
 [0 8 2]
 [3 6 4]]
Matrix B:
 [[8 7]
 [6 7]
 [8 5]]
Multiplication matrix:
 [[ 48  49]
 [166 143]
 [ 80  69]
 [ 64  66]
 [ 92  83]]


## 6.WAP to create a numpy to input two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

## 7.WAP to print all the values of an array