## 1.WAP using numpy input two arrays as A=(1,0) and B=(0,1) and calcuate two new arrays as C = 1/sqrt(2)(A+B) D = 1/sqrt(2)(A+B)

In [2]:
import numpy as np

In [17]:
A=np.array([1,0])
B=np.array([0,1])
res=np.sqrt(2)
C=(A+B)*res
print(C)
D=(A+B)*res
print(D)

[1.41421356 1.41421356]
[1.41421356 1.41421356]


## 2.WAP using numpy to create a matrix A of 2x2 then find the size of A and print element (1,1) of A

In [15]:
A=np.matrix('[1,2;5,6]')
np.shape(A)
print(A)
A[1,1]

[[1 2]
 [5 6]]


6

## 3.WAP using numpy to find an element in an array

In [6]:
import time
A=np.array([1,0,5,10,2,6])
print(A)
time.sleep(1)
n=int(input("enter the number you want to search:"))
#if n in A:
 #   print(f'{n} fOUND!')
#else:
#    print(f'{n} NOT FOUND!!')
x = np.where(A == n)
print(x)

[ 1  0  5 10  2  6]
enter the number you want to search:4
(array([], dtype=int64),)


## 4.WAP using numpy to sort an array

In [13]:
a = np.array([[12, 15,10, 1]]) 
arr1 = np.sort(a, axis = None)         
print ("Ascending order : ", arr1) 

Ascending order :  [ 1 10 12 15]


## 5.WAP using numpy to sort a 2D array

In [28]:
a = np.array([[12, 15], [10, 1]]) 
print(a)
arr1 = np.sort(a, axis = -1)      
print ("Along first axis : \n", arr1)

[[12 15]
 [10  1]]
Along first axis : 
 [[12 15]
 [ 1 10]]


## 6.WAP using numpy to add elements of diagnols

In [36]:
A=np.matrix('[1,2,3;4,5,6;7,8,9]')
print("matrix: \n",A)
res=A.diagonal()
print("diagonal:",res)
trace = np.trace(A) 
print("sum of diagonal: ",trace)

matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal: [[1 5 9]]
sum of diagonal:  15


## 7.WAP using numpy to add elements of diagnols and find which one is greater

In [39]:
A=np.matrix('[1,2,3;4,5,6;7,8,9]')
print("matrix: \n",A)
res=A.diagonal()
print("diagonal:",res)
trace = np.trace(A) #to sum the diagonals
print("sum of diagonal: ",trace)
print("max in diagonal:",np.max(res))

matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal: [[1 5 9]]
sum of diagonal:  15
max in diagonal: 9
